version: '3.9'

services:
  book-db:
    image: postgres
    container_name: book-db
    environment:
      POSTGRES_USER: book
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_db
    ports:
      - "5432:5432"
    volumes:
      - book-db-data:/var/lib/postgresql/data
    env_file:
      - ./book-service/.env

  order-db:
    image: postgres
    container_name: order-db
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    env_file:
      - ./order-service/.env

  book-service:
    build: ./book-service
    ports:
      - "4000:4000"
    depends_on:
      - book-db
    volumes:
      - ./book-service/src:/usr/src/app/src
    environment:
      DATABASE_HOST: book-db
      DATABASE_PORT: 5432
      DATABASE_USER: book
      DATABASE_PASSWORD: password
      DATABASE_NAME: book_db


  order-service:
    build: ./order-service
    ports:
      - "4001:4000"
    depends_on:
      - order-db
    volumes:
      - ./order-service/src:/usr/src/app/src
    environment:
      DATABASE_HOST: order-db
      DATABASE_PORT: 5432
      DATABASE_USER: order
      DATABASE_PASSWORD: password
      DATABASE_NAME: order_db

  gateway-service:
    build: ./gateway
    ports:
      - "3002:3000"
    depends_on:
      - book-service
      - order-service
    volumes:
      - ./gateway/src:/usr/src/app/src
    environment:
      BOOK_SERVICE_URL: http://book-service:4000
      ORDER_SERVICE_URL: http://order-service:4000

volumes:
  book-db-data:
  order-db-data:
